[phases.setup]
nixPkgs = ["python311", "gcc", "gfortran", "openblas", "lapack"]

[phases.install]
cmds = [
  "pip install --upgrade pip setuptools wheel",
  "pip install numpy==1.24.3",
  "pip install scikit-learn==1.3.0 --no-build-isolation",
  "pip install --no-cache-dir -r requirements.txt"
]

[start]
cmd = "python nba_flask_api.py"
