name: Check Predictions Daily

on:
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:

jobs:
  check-predictions:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install Dependencies
        run: |
          pip install requests nba-api pandas numpy joblib scikit-learn
      
      - name: Check Yesterday's Predictions
        env:
          RAILWAY_API_URL: ${{ secrets.RAILWAY_API_URL }}
        run: |
          python live_prediction_checker.py
      
      - name: Success Notification
        if: success()
        run: |
          echo "✅ Predictions checked successfully!"
